In [15]:
import sqlite3
import pandas as pd

con = sqlite3.connect('database.db')
cur = con.cursor()


pd.read_sql_query("""SELECT name FROM sqlite_master WHERE type='table';""", con)

         name
0  instrument
1   pricedata

In [18]:
pd.read_sql_query("""SELECT * FROM instrument;""", con)

   id     name  symbol timeframe
0   1  EUR/USD  EURUSD        D1
1   2  EUR/USD  EURUSD        H1
2   3  EUR/USD  EURUSD        H4
3   4  EUR/USD  EURUSD        M1
4   5  EUR/USD  EURUSD        M5
5   6  EUR/USD  EURUSD       M15
6   7  EUR/USD  EURUSD       M30

In [19]:
pd.read_sql_query("""SELECT * FROM pricedata;""", con)

,id,time,instrument_id,open,high,low,close,volume
0,1,2010-03-03 00:00:00.000000,1,1.36185,1.37356,1.35898,1.36999,80416
1,2,2010-03-04 00:00:00.000000,1,1.37003,1.37108,1.35504,1.35810,80310
2,3,2010-03-05 00:00:00.000000,1,1.35807,1.36297,1.35288,1.36222,75820
3,4,2010-03-08 00:00:00.000000,1,1.36353,1.37038,1.36038,1.36147,79541
4,5,2010-03-09 00:00:00.000000,1,1.36148,1.36348,1.35337,1.36046,79331
...,...,...,...,...,...,...,...,...
909983,909984,2026-03-13 18:30:00.000000,7,1.14359,1.14406,1.14348,1.14359,2459
909984,909985,2026-03-13 19:00:00.000000,7,1.14360,1.14368,1.14243,1.14251,2079
909985,909986,2026-03-13 19:30:00.000000,7,1.14250,1.14278,1.14197,1.14222,1663
909986,909987,2026-03-13 20:00:00.000000,7,1.14223,1.14226,1.14130,1.14145,1440
909987,909988,2026-03-13 20:30:00.000000,7,1.14144,1.14174,1.14108,1.14161,1794