In [2]:
import sqlite3
import pandas as pd

con = sqlite3.connect('database.db')
cur = con.cursor()


pd.read_sql_query("""SELECT name FROM sqlite_master WHERE type='table';""", con)

         name
0  instrument
1      domain
2   pricedata

In [3]:
pd.read_sql_query("""SELECT * FROM instrument;""", con)

   id     name  symbol timeframe
0   1  EUR/USD  EURUSD        D1
1   2  EUR/USD  EURUSD        H1
2   3  EUR/USD  EURUSD        H4
3   4  EUR/USD  EURUSD        M1
4   5  EUR/USD  EURUSD        M5
5   6  EUR/USD  EURUSD       M15
6   7  EUR/USD  EURUSD       M30

In [4]:
pd.read_sql_query("""SELECT * FROM pricedata;""", con)

,id,time,instrument_id,open,high,low,close,volume,domain_id
0,1,2010-03-03 00:00:00.000000,1,1.36185,1.37356,1.35898,1.36999,80416,1
1,2,2010-03-04 00:00:00.000000,1,1.37003,1.37108,1.35504,1.35810,80310,1
2,3,2010-03-05 00:00:00.000000,1,1.35807,1.36297,1.35288,1.36222,75820,1
3,4,2010-03-08 00:00:00.000000,1,1.36353,1.37038,1.36038,1.36147,79541,2
4,5,2010-03-09 00:00:00.000000,1,1.36148,1.36348,1.35337,1.36046,79331,2
...,...,...,...,...,...,...,...,...,...
909983,909984,2026-03-13 18:30:00.000000,7,1.14359,1.14406,1.14348,1.14359,2459,4648
909984,909985,2026-03-13 19:00:00.000000,7,1.14360,1.14368,1.14243,1.14251,2079,4648
909985,909986,2026-03-13 19:30:00.000000,7,1.14250,1.14278,1.14197,1.14222,1663,4648
909986,909987,2026-03-13 20:00:00.000000,7,1.14223,1.14226,1.14130,1.14145,1440,4648
909987,909988,2026-03-13 20:30:00.000000,7,1.14144,1.14174,1.14108,1.14161,1794,4648

In [5]:
# pd.read_sql_query("""SELECT * FROM domain;""", con)
# show datatypes of columns in domain table

In [6]:

pd.read_sql_query("""SELECT * FROM pricedata WHERE instrument_id = 5;""", con)

,id,time,instrument_id,open,high,low,close,volume,domain_id
0,323132,2023-07-10 04:45:00.000000,5,1.09565,1.09566,1.09548,1.09556,797,3151
1,323133,2023-07-10 04:50:00.000000,5,1.09554,1.09556,1.09537,1.09541,645,3151
2,323134,2023-07-10 04:55:00.000000,5,1.09542,1.09547,1.09525,1.09530,1192,3151
3,323135,2023-07-10 05:00:00.000000,5,1.09529,1.09552,1.09526,1.09537,1364,3151
4,323136,2023-07-10 05:05:00.000000,5,1.09539,1.09561,1.09532,1.09557,728,3151
...,...,...,...,...,...,...,...,...,...
195683,518815,2026-03-13 20:35:00.000000,5,1.14119,1.14121,1.14109,1.14111,153,3347
195684,518816,2026-03-13 20:40:00.000000,5,1.14115,1.14129,1.14108,1.14129,127,3347
195685,518817,2026-03-13 20:45:00.000000,5,1.14129,1.14139,1.14120,1.14139,312,3347
195686,518818,2026-03-13 20:50:00.000000,5,1.14138,1.14150,1.14120,1.14140,481,3347
195687,518819,2026-03-13 20:55:00.000000,5,1.14138,1.14174,1.14136,1.14161,510,3347

In [10]:
# show domains table
pd.read_sql_query("SELECT * FROM domain;", con)

        id             time_min             time_max  instrument_id
0        1  2010-03-03 00:00:00  2010-03-05 00:00:00              1
1        2  2010-03-03 00:00:00  2010-03-05 00:00:00              1
2        3  2010-03-03 00:00:00  2010-03-05 00:00:00              1
3        4  2010-03-03 00:00:00  2010-03-05 00:00:00              1
4        5  2010-03-03 00:00:00  2010-03-05 00:00:00              1
...    ...                  ...                  ...            ...
4643  4644  2010-03-02 04:00:00  2010-03-05 21:30:00              7
4644  4645  2010-03-02 04:00:00  2010-03-05 21:30:00              7
4645  4646  2010-03-02 04:00:00  2010-03-05 21:30:00              7
4646  4647  2010-03-02 04:00:00  2010-03-05 21:30:00              7
4647  4648  2010-03-02 04:00:00  2010-03-05 21:30:00              7

[4648 rows x 4 columns]